apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRVk5hZE40VGVsYWltU2lhTllKZzA0akFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTJNREV6TVRBNE1qZ3dNRm9YRFRNMk1ERXlPVEE0TWpndwpNRm93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCS0U2enp5bStZK2E2QnV2VEoycHkxeDRjWndZWTBFK1cyYmhMTE5FZ3llME02cmdrb3R6NDZPblRoa2EKQWN5cFU1SzVVWmVnTnlicXhmNkhMMGRZRGxDallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVmbHAzNTJxSG8wT1Q1SzRDTXdGRUhpV21SRGd3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUpKZFJOTkEKbnliT21YaCtTK2N3L0owTTAybTE3ejlwOXRyTzRlVDN2UjBGQWlBSXdOM3hrWnMwZ2JSajlQN3BPdU5tYU5tNAovbmlGYUdkYkd2bGNtN01ES0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://46.225.62.225:6443
  name: talos-k8s
contexts:
- context:
    cluster: talos-k8s
    namespace: default
    user: admin@talos-k8s
  name: admin@talos-k8s
current-context: admin@talos-k8s
kind: Config
users:
- name: admin@talos-k8s
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoRENDQVNxZ0F3SUJBZ0lRQ2NVSlp2U2JHb2tHNitkamhwNzFJREFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTJNREV6TVRBNE16QXlNbG9YRFRJM01ERXpNVEE0TXpBegpNbG93S1RFWE1CVUdBMVVFQ2hNT2MzbHpkR1Z0T20xaGMzUmxjbk14RGpBTUJnTlZCQU1UQldGa2JXbHVNRmt3CkV3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFaUZyRFNyNGVxci9mSzN1QVFmcmF3SXZlVVVTNDJGTXgKdjFWOTcxcW1uY2NPeW1FdmttdFZDVjZyeW85aENqTG91RjY3bWRpY3A2TWtFTTFFSkE0eWlhTklNRVl3RGdZRApWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01COEdBMVVkSXdRWU1CYUFGSDVhCmQrZHFoNk5EaytTdUFqTUJSQjRscGtRNE1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRRC9VRFRqZG41WG9ZMU4KMlFia3IrMVdORGthVjB4WEs3WkVKaDQwa0M1QVhRSWdLeXhlRjR4NVdHeXZ4L1g2dHdzbXlCRkVtako2bWhxUgpTS1hXQzFjR2FtOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUcrVElia0QwTmVqMUx5VjJsVExDdkZoWDR3eUF0MVlaMUJtVmtXdHAvd0NvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFaUZyRFNyNGVxci9mSzN1QVFmcmF3SXZlVVVTNDJGTXh2MVY5NzFxbW5jY095bUV2a210VgpDVjZyeW85aENqTG91RjY3bWRpY3A2TWtFTTFFSkE0eWlRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=

